Fix log symlinking in post-receive script

diff --git a/scripts/post-receive b/scripts/post-receive
--- a/scripts/post-receive
+++ b/scripts/post-receive
@@ -17,7 +17,7 @@ DATESTAMP=$(date +"%Y%m%d%H%M%S")
 RELEASE_PATH="$DEPLOY_BASE_PATH/releases/$DATESTAMP"
 CURRENT_PATH="$DEPLOY_BASE_PATH/current"
 SHARED_PATH="$DEPLOY_BASE_PATH/shared"
-LOG_PATH="$DEPLOY_BASE_PATH/shared/logs"
+LOG_PATH="$DEPLOY_BASE_PATH/shared/log"
 PRESTART_URL="https://snap-test.its.sfu.ca/isup"
 PIDFILE="/var/run/nginx.pid"
 
@@ -49,8 +49,8 @@ cd $RELEASE_PATH && npm run build || { echo "Error running `npm run build`" ; ex
 echo "Symlink config files"
 ln -s $SHARED_PATH/config/.env.production $RELEASE_PATH || { echo "Error symlinking .env.production" ; exit 1; }
 
-# symlink logs & pid
-ln -s $SHARED_PATH/{logs,pid} $RELEASE_PATH || { echo "Error symlinking logs & pid" ; exit 1; }
+# symlink logs
+ln -s $SHARED_PATH/{log} $RELEASE_PATH || { echo "Error symlinking logs" ; exit 1; }
 
 # move symlink
 echo "Move symlink"
